### PR TITLE
Add blue border on .btn-link:focus, and Proper "Proper fix #179"

### LINKED ISSUE #179: Should no :focus outline when :active
Note:
Browser add `focus` and `active` status when you ~~~_mouseup_~~~ mousedown a element

---

### Now
https://todc.github.io/todc-bootstrap/css/#buttons-options
2017-03-27 19_40_41-css todc bootstrap

---

### Expect
https://translate.google.com
2017-03-27 19_41_32-google translate

### PR DESCRIPTION
**Pull request by zcyzcy88**
### Add blue border on `.btn-link:focus`
2017-03-30 00_13_19-css todc bootstrap

---

### Proper "Proper fix #179"
It wrong at CSS priority.
My wrong fix:
2017-03-29 22_30_00-css todc bootstrap
Expect:
2017-03-29 22_29_50-css todc bootstrap

---

Some reason cause I can't build, so you should build and test.

### CODE REVIEW

**Comment by acmetech** [comment]
Hi @zcyzcy88,

Do you have an example, on a Google site, of the link button with the blue border on focus?

Thanks

**Comment by zcyzcy88** [comment]
Drive:
2017-03-30 03_30_24-my drive - google drive

---

Translate:
2017-03-30 03_31_31-google translate

---

YouTube:
2017-03-30 03_32_23- - youtube

---

Docs:
2017-03-30 03_34_45-google docs

**Comment by acmetech** [comment]
The only one of the examples that might be a  btn-link is the one from Google Translate, but I think that it is more like a customized btn-default.

I don't have a problem adding the border-color to btn-link on focus, but I don't think it should be added on hover and active.

Google Drive and Docs are more equivalent to http://localhost:9002/components/#navbar-toolbar-default

YouTube is more equivalent to this, http://localhost:9002/components/#nav-tabs.

The focus outline/border colors for the above components have probably changed since the components were last updated.

**Comment by zcyzcy88** [comment]
This is an accessibility improvement for keyboard navigation.
Since all native `<a>` link outlined when focus, I think `.btn-link` should have too.

Adding border to `:active` and `:hover` is a mistake, I will fix.

**Comment by acmetech** [comment]
Thanks. I'll build build todc-bootstrap and merge it.

**Pull request merged**
